import { Inter } from "next/font/google";
// import "./globals.css";
import "../../public/styles/global.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Welcome to Patel's Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
